// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/binaryauthorization/v1beta1/resources.proto

package com.google.cloud.binaryauthorization.v1beta1;

public interface AdmissionWhitelistPatternOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.binaryauthorization.v1beta1.AdmissionWhitelistPattern)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An image name pattern to allow, in the form `registry/path/to/image`.
   * This supports a trailing `*` as a wildcard, but this is allowed only in
   * text after the `registry/` part.
   * </pre>
   *
   * <code>string name_pattern = 1;</code>
   * @return The namePattern.
   */
  java.lang.String getNamePattern();
  /**
   * <pre>
   * An image name pattern to allow, in the form `registry/path/to/image`.
   * This supports a trailing `*` as a wildcard, but this is allowed only in
   * text after the `registry/` part.
   * </pre>
   *
   * <code>string name_pattern = 1;</code>
   * @return The bytes for namePattern.
   */
  com.google.protobuf.ByteString
      getNamePatternBytes();
}
